baseurl = "https://hackerberg.pages.dev/"
theme = "hugo_theme_pickles"
languageCode = "zh-CN"
title = "Hackerberg"
copyright = "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International"
enableGitInfo = true
paginate = 20

[params]
  hideWordCount = true
  hideReadingTime = true
  custom_css = ["/css/custom.css"]
  author = "Hackerberg"
  authorwebsite = "hackerberg.pages.dev"
  avatar = "/255713183.png"
  logo = "/255713183.png"
  favicon = "/favicon.ico"
  contact = "mailto:hackerberg@proton.me"
  bio = "黑客境"
  subtitle = "黑客境"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

[related]
  threshold = 80
  includeNewer = false
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  
  [[related.indices]]
  name  = "tags"
  weight = 100
  
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
